"""Added dislike model

Revision ID: 959c928a5893
Revises: 4913feafe780
Create Date: 2020-12-16 19:44:15.821098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '959c928a5893'
down_revision = '4913feafe780'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_dislikes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_dislikes')
    # ### end Alembic commands ###
