"""Added image captions

Revision ID: d4f50aedad9e
Revises: 08bb2065ea00
Create Date: 2020-12-16 16:23:51.935250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4f50aedad9e'
down_revision = '08bb2065ea00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_images', sa.Column('caption', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_images', 'caption')
    # ### end Alembic commands ###
