"""Updated posts for dislikes

Revision ID: f8c8d0810fd5
Revises: 959c928a5893
Create Date: 2020-12-16 19:46:12.518319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8c8d0810fd5'
down_revision = '959c928a5893'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('total_dislikes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'total_dislikes')
    # ### end Alembic commands ###
